[package]
name = "skydock-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
skydock-core = { version = "0.1.0", path = "../core" }
skydock-service = { version = "0.1.0", path = "../service" }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "signal"] }

[[bin]]
name = "skydock"
path = "src/main.rs"
