[package]
name = "skydock-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fuser = { version = "0.18.0", default-features = false }
nix = { version = "0.31.3", features = ["fs"] }
sha2 = "0.11.0"
skydock-core = { version = "0.1.0", path = "../core" }
skydock-state = { version = "0.1.0", path = "../state" }
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["rt", "sync", "time"] }

[dev-dependencies]
async-trait = "0.1.92"
reqwest = { version = "0.13.5", default-features = false }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "fs"] }
