[package]
name = "skydock-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.92"
base64 = "0.23.1"
md-5 = "0.11.0"
oo7 = "0.6.0"
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "json", "form", "query", "http2"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["net", "io-util", "time", "sync", "process", "macros", "fs"] }
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.2", features = ["rt", "macros"] }
